[#] [FEATURE] Scripts pour importer les tutoriels et les tags dans la table Acquis (US-1026).
pix-fr/airtable-updater pull request #1
Opened 2018-03-06 14:56 UTC by MBrandone

2018-03-26 15:03 UTC, mlaurent requested changes

2018-03-26 15:03 UTC, mlaurent commented on index.js
> +    console.error(`please specify the environnement variable.`);
Qui nous dit que l'argument manquant est celui concernant l'environnement ?
Il faudrait un message disant qu'un seul argument a été donnée alors qu'on s'attend à 2 (command et env)

2018-03-26 15:03 UTC, mlaurent commented on index.js
> +const environnements = {
'Environments' en Anglais

2018-03-26 15:03 UTC, mlaurent commented on lib/controllers/import_additional_tutorials_skills_20180307.js
> +async function run() {
Cette manière de faire est très procédurale.
Est-ce qu'on ne pourrait pas être plus fonctionnel, en supprimant le context partagé, et en fonctionnant avec un enchainement de fonctions qui prennent des arguments et renvoient un résultat ?

2018-03-26 15:03 UTC, mlaurent commented on lib/repositories/skill-repository.js
> +    async addAdditionalTutorial(recordId, tutorials) {
addAdditionalTutorial**s** ?

2018-03-27 09:47 UTC, MBrandone commented on index.js
> +    console.error(`please specify the environnement variable.`);
done. Les nouveaux messages disent qu'il y a un arguments manquant, qu'il faut une command en premier en listant les possibilités, et un environnement en deuxième en listant les possibilités.

2018-03-27 09:48 UTC, MBrandone commented on index.js
> +const environnements = {
changé

2018-03-27 09:49 UTC, MBrandone commented on lib/controllers/import_additional_tutorials_skills_20180307.js
> +async function run() {
Totalement vrai, on en tiendra compte sur des potentielles futurs scripts.

2018-03-27 09:54 UTC, MBrandone commented on lib/repositories/skill-repository.js
> +    async addAdditionalTutorial(recordId, tutorials) {
yes

2018-03-27 09:58 UTC, mlaurent approved these changes

2018-03-27 09:58 UTC, merged